// <auto-generated />
using System;
using Lapostemobile_portail.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lapostemobile_portail.Migrations
{
    [DbContext(typeof(PortailContext))]
    [Migration("20230915193024_mig")]
    partial class mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lapostemobile_portail.Models.Adresse", b =>
                {
                    b.Property<int>("IdAdresse")
                        .HasColumnType("int")
                        .HasColumnName("id_adresse");

                    b.Property<string>("AdresseComp")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("adresse_comp");

                    b.Property<string>("Codepostal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("codepostal");

                    b.Property<DateTime?>("DatCre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("dat_cre")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DatMod")
                        .HasColumnType("date")
                        .HasColumnName("dat_mod");

                    b.Property<int>("IdPays")
                        .HasColumnType("int")
                        .HasColumnName("id_pays");

                    b.Property<string>("Numero")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("numero");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ville");

                    b.Property<string>("Voie")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("voie");

                    b.HasKey("IdAdresse")
                        .HasName("PK__adresse__05B3E6DC602BFAB6");

                    b.ToTable("adresse", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Article", b =>
                {
                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<string>("CodeSap")
                        .HasMaxLength(18)
                        .IsUnicode(false)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("code_sap");

                    b.Property<DateTime?>("DateFinCcial")
                        .HasColumnType("date")
                        .HasColumnName("date_fin_ccial");

                    b.Property<string>("FichierImage")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("fichier_image");

                    b.Property<string>("FichierImageVignette")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("fichier_image_vignette");

                    b.Property<int?>("IdFabriquant")
                        .HasColumnType("int")
                        .HasColumnName("id_fabriquant");

                    b.Property<int>("IdTypeArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_type_article");

                    b.Property<string>("LibelleArticle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("libelle_article");

                    b.Property<string>("LibelleCourt")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("libelle_court");

                    b.Property<int?>("Ordre")
                        .HasColumnType("int")
                        .HasColumnName("ordre");

                    b.Property<bool>("Statut")
                        .HasColumnType("bit")
                        .HasColumnName("statut");

                    b.HasKey("IdArticle")
                        .HasName("PK__article__64CB31B82888E3FD");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.CaracteristiquesArticle", b =>
                {
                    b.Property<int>("IdCaracteristiquesArticles")
                        .HasColumnType("int")
                        .HasColumnName("id_caracteristiques_articles");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<string>("NomCaracteristiquesArticles")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nom_caracteristiques_articles");

                    b.Property<string>("ValeurCarasteristiquesArticles")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("valeur_carasteristiques_articles");

                    b.HasKey("IdCaracteristiquesArticles")
                        .HasName("PK__caracter__6F85FECF37650E6D");

                    b.HasIndex("IdArticle");

                    b.ToTable("caracteristiques_articles", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.CoordonneesBancaire", b =>
                {
                    b.Property<int>("IdCoordonnees")
                        .HasColumnType("int")
                        .HasColumnName("id_coordonnees");

                    b.Property<string>("CodeBic")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("code_bic");

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("date")
                        .HasColumnName("date_modification");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .IsUnicode(false)
                        .HasColumnType("varchar(34)")
                        .HasColumnName("iban");

                    b.Property<string>("NomBanque")
                        .HasMaxLength(58)
                        .IsUnicode(false)
                        .HasColumnType("varchar(58)")
                        .HasColumnName("nom_banque");

                    b.Property<string>("TitulaireCompte")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("titulaire_compte");

                    b.HasKey("IdCoordonnees")
                        .HasName("PK__coordonn__AF9E03123FB3761A");

                    b.ToTable("coordonnees_bancaires", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Financement", b =>
                {
                    b.Property<int>("IdFinancement")
                        .HasColumnType("int")
                        .HasColumnName("id_financement");

                    b.Property<decimal>("DureeFinancement")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("duree_financement");

                    b.Property<int>("IdOption")
                        .HasColumnType("int")
                        .HasColumnName("id_option");

                    b.Property<decimal>("MontantFinancement")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("montant_financement");

                    b.HasKey("IdFinancement")
                        .HasName("PK__financem__A9EB9E164074079B");

                    b.HasIndex("IdOption");

                    b.ToTable("financement", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Ligne", b =>
                {
                    b.Property<int>("IdLigne")
                        .HasColumnType("int")
                        .HasColumnName("id_ligne");

                    b.Property<DateTime?>("DatCre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("dat_cre")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DatMod")
                        .HasColumnType("date")
                        .HasColumnName("dat_mod");

                    b.Property<int?>("IdFinancement")
                        .HasColumnType("int")
                        .HasColumnName("id_financement");

                    b.Property<int?>("IdOffreEngagement")
                        .HasColumnType("int")
                        .HasColumnName("id_offre_engagement");

                    b.Property<int>("IdSouscription")
                        .HasColumnType("int")
                        .HasColumnName("id_souscription");

                    b.Property<decimal>("PrixVenteOffre")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("prix_vente_offre");

                    b.HasKey("IdLigne")
                        .HasName("PK__ligne__E1D60C0C35DB3C13");

                    b.HasIndex("IdFinancement");

                    b.HasIndex("IdOffreEngagement");

                    b.HasIndex("IdSouscription");

                    b.ToTable("ligne", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.LigneArticle", b =>
                {
                    b.Property<int>("IdLigneArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_ligne_article");

                    b.Property<DateTime?>("DatCre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("dat_cre")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DatMod")
                        .HasColumnType("date")
                        .HasColumnName("dat_mod");

                    b.Property<int?>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int>("IdLigne")
                        .HasColumnType("int")
                        .HasColumnName("id_ligne");

                    b.Property<string>("Imei")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("imei");

                    b.Property<decimal?>("PrixPaye")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("prix_paye");

                    b.Property<decimal?>("TotalSubvention")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("total_subvention");

                    b.HasKey("IdLigneArticle")
                        .HasName("PK__ligne_ar__813AC43D1DD68471");

                    b.HasIndex("IdLigne");

                    b.ToTable("ligne_article", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.LigneOption", b =>
                {
                    b.Property<int>("IdLigneOption")
                        .HasColumnType("int")
                        .HasColumnName("id_ligne_option");

                    b.Property<DateTime?>("DatMod")
                        .HasColumnType("date")
                        .HasColumnName("dat_mod");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("date")
                        .HasColumnName("date_creation");

                    b.Property<int>("IdLigne")
                        .HasColumnType("int")
                        .HasColumnName("id_ligne");

                    b.Property<int?>("IdOption")
                        .HasColumnType("int")
                        .HasColumnName("id_option");

                    b.Property<int>("PrixVenteOption")
                        .HasColumnType("int")
                        .HasColumnName("prix_vente_option");

                    b.HasKey("IdLigneOption")
                        .HasName("PK__ligne_op__6498FBB40410619C");

                    b.HasIndex("IdLigne");

                    b.HasIndex("IdOption");

                    b.ToTable("ligne_option", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.ModeLivraison", b =>
                {
                    b.Property<int>("IdModeLivraison")
                        .HasColumnType("int")
                        .HasColumnName("id_mode_livraison");

                    b.Property<string>("LibelleModeLivraison")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("libelle_mode_livraison");

                    b.HasKey("IdModeLivraison")
                        .HasName("PK__mode_liv__C95298B7B962A58E");

                    b.ToTable("mode_livraison", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.OffreEngagement", b =>
                {
                    b.Property<int>("IdOffreEngagement")
                        .HasColumnType("int")
                        .HasColumnName("id_offre_engagement");

                    b.Property<string>("Caracteristiques")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("caracteristiques");

                    b.Property<int>("DureeEngagement")
                        .HasColumnType("int")
                        .HasColumnName("duree_engagement");

                    b.Property<bool?>("Est5g")
                        .HasColumnType("bit")
                        .HasColumnName("est_5g");

                    b.Property<string>("LibelleMarketing")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("libelle_marketing");

                    b.Property<decimal>("MontantSubvention")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("montant_subvention");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("prix");

                    b.HasKey("IdOffreEngagement")
                        .HasName("PK__offre_en__857BF79C0AC2E96F");

                    b.ToTable("offre_engagement", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Option", b =>
                {
                    b.Property<int>("IdOption")
                        .HasColumnType("int")
                        .HasColumnName("id_option");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<int>("IdGroupeOption")
                        .HasColumnType("int")
                        .HasColumnName("id_groupe_option");

                    b.Property<string>("LibelleMarketing")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("libelle_marketing");

                    b.Property<string>("LibelleOption")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("libelle_option");

                    b.Property<decimal?>("OrdreAffichage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("ordre_affichage")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("IdOption")
                        .HasName("PK__options__7B78D9B64C0BC083");

                    b.ToTable("options", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.PrixArticle", b =>
                {
                    b.Property<int>("IdPrixArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_prix_article");

                    b.Property<DateTime?>("DateInsert")
                        .HasColumnType("date")
                        .HasColumnName("date_insert");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int>("IdOffreEngagement")
                        .HasColumnType("int")
                        .HasColumnName("id_offre_engagement");

                    b.Property<decimal?>("PrixArticle1")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("prix_article");

                    b.HasKey("IdPrixArticle")
                        .HasName("PK__prix_art__B64515C8F009DBA4");

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdOffreEngagement");

                    b.ToTable("prix_article", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Prospect", b =>
                {
                    b.Property<int>("IdProspect")
                        .HasColumnType("int")
                        .HasColumnName("id_prospect");

                    b.Property<DateTime?>("DatCre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("dat_cre")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DatMod")
                        .HasColumnType("date")
                        .HasColumnName("dat_mod");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("date_naissance");

                    b.Property<string>("DepNaissance")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("dep_naissance");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("email");

                    b.Property<int?>("IdAdresseFacturation")
                        .HasColumnType("int")
                        .HasColumnName("id_adresse_facturation");

                    b.Property<int?>("IdAdresseLivraison")
                        .HasColumnType("int")
                        .HasColumnName("id_adresse_livraison");

                    b.Property<int>("IdCivilite")
                        .HasColumnType("int")
                        .HasColumnName("id_civilite");

                    b.Property<int?>("IdCoordonneesBancaires")
                        .HasColumnType("int")
                        .HasColumnName("id_coordonnees_bancaires");

                    b.Property<int>("IdModepaiementSouscription")
                        .HasColumnType("int")
                        .HasColumnName("id_modepaiement_souscription");

                    b.Property<int>("IdSouscription")
                        .HasColumnType("int")
                        .HasColumnName("id_souscription");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("nom");

                    b.Property<string>("NumeroFixe")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("numero_fixe");

                    b.Property<string>("NumeroMobile")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("numero_mobile");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("prenom");

                    b.HasKey("IdProspect")
                        .HasName("PK__prospect__6B3AC313077C5DF6");

                    b.HasIndex("IdCoordonneesBancaires");

                    b.ToTable("prospect", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Souscription", b =>
                {
                    b.Property<int>("IdSouscription")
                        .HasColumnType("int")
                        .HasColumnName("id_souscription");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("date")
                        .HasColumnName("date_modification");

                    b.Property<DateTime>("DateSouscription")
                        .HasColumnType("date")
                        .HasColumnName("date_souscription");

                    b.Property<decimal>("IdModeLivraison")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("id_mode_livraison");

                    b.Property<int>("IdStatutSouscription")
                        .HasColumnType("int")
                        .HasColumnName("id_statut_souscription");

                    b.Property<decimal?>("MontantPaye")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("montant_paye");

                    b.Property<string>("NumContrat")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("num_contrat");

                    b.Property<decimal?>("PrixLivraison")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("prix_livraison");

                    b.HasKey("IdSouscription")
                        .HasName("PK__souscrip__A5BABA325DC0888D");

                    b.HasIndex("IdStatutSouscription");

                    b.ToTable("souscription", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.StatutSouscription", b =>
                {
                    b.Property<int>("IdStatutSouscription")
                        .HasColumnType("int")
                        .HasColumnName("id_statut_souscription");

                    b.Property<decimal>("EstSouscriptionComplete")
                        .HasColumnType("numeric(1, 0)")
                        .HasColumnName("est_souscription_complete");

                    b.Property<string>("LibelleStatutSouscription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("libelle_statut_souscription");

                    b.HasKey("IdStatutSouscription")
                        .HasName("PK__statut_s__DA50E02423CA42C6");

                    b.ToTable("statut_souscription", (string)null);
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.CaracteristiquesArticle", b =>
                {
                    b.HasOne("Lapostemobile_portail.Models.Article", "IdArticleNavigation")
                        .WithMany("CaracteristiquesArticles")
                        .HasForeignKey("IdArticle")
                        .IsRequired()
                        .HasConstraintName("FK__caracteri__id_ar__60A75C0F");

                    b.Navigation("IdArticleNavigation");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Financement", b =>
                {
                    b.HasOne("Lapostemobile_portail.Models.Option", "IdOptionNavigation")
                        .WithMany("Financements")
                        .HasForeignKey("IdOption")
                        .IsRequired()
                        .HasConstraintName("FK__financeme__id_op__49C3F6B7");

                    b.Navigation("IdOptionNavigation");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Ligne", b =>
                {
                    b.HasOne("Lapostemobile_portail.Models.Financement", "IdFinancementNavigation")
                        .WithMany("Lignes")
                        .HasForeignKey("IdFinancement")
                        .HasConstraintName("FK__ligne__id_financ__5165187F");

                    b.HasOne("Lapostemobile_portail.Models.OffreEngagement", "IdOffreEngagementNavigation")
                        .WithMany("Lignes")
                        .HasForeignKey("IdOffreEngagement")
                        .HasConstraintName("FK__ligne__id_offre___52593CB8");

                    b.HasOne("Lapostemobile_portail.Models.Souscription", "IdSouscriptionNavigation")
                        .WithMany("Lignes")
                        .HasForeignKey("IdSouscription")
                        .IsRequired()
                        .HasConstraintName("FK__ligne__id_souscr__534D60F1");

                    b.Navigation("IdFinancementNavigation");

                    b.Navigation("IdOffreEngagementNavigation");

                    b.Navigation("IdSouscriptionNavigation");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.LigneArticle", b =>
                {
                    b.HasOne("Lapostemobile_portail.Models.Ligne", "IdLigneNavigation")
                        .WithMany("LigneArticles")
                        .HasForeignKey("IdLigne")
                        .IsRequired()
                        .HasConstraintName("FK__ligne_art__id_li__59FA5E80");

                    b.Navigation("IdLigneNavigation");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.LigneOption", b =>
                {
                    b.HasOne("Lapostemobile_portail.Models.Ligne", "IdLigneNavigation")
                        .WithMany("LigneOptions")
                        .HasForeignKey("IdLigne")
                        .IsRequired()
                        .HasConstraintName("FK__ligne_opt__id_li__5CD6CB2B");

                    b.HasOne("Lapostemobile_portail.Models.Option", "IdOptionNavigation")
                        .WithMany("LigneOptions")
                        .HasForeignKey("IdOption")
                        .HasConstraintName("FK__ligne_opt__id_op__5DCAEF64");

                    b.Navigation("IdLigneNavigation");

                    b.Navigation("IdOptionNavigation");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.PrixArticle", b =>
                {
                    b.HasOne("Lapostemobile_portail.Models.Article", "IdArticleNavigation")
                        .WithMany("PrixArticles")
                        .HasForeignKey("IdArticle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_prix_article_article");

                    b.HasOne("Lapostemobile_portail.Models.OffreEngagement", "IdOffreEngagementNavigation")
                        .WithMany("PrixArticles")
                        .HasForeignKey("IdOffreEngagement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_prix_article_offre_engagement");

                    b.Navigation("IdArticleNavigation");

                    b.Navigation("IdOffreEngagementNavigation");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Prospect", b =>
                {
                    b.HasOne("Lapostemobile_portail.Models.CoordonneesBancaire", "IdCoordonneesBancairesNavigation")
                        .WithMany("Prospects")
                        .HasForeignKey("IdCoordonneesBancaires")
                        .HasConstraintName("FK__prospect__id_coo__3D5E1FD2");

                    b.Navigation("IdCoordonneesBancairesNavigation");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Souscription", b =>
                {
                    b.HasOne("Lapostemobile_portail.Models.StatutSouscription", "IdStatutSouscriptionNavigation")
                        .WithMany("Souscriptions")
                        .HasForeignKey("IdStatutSouscription")
                        .IsRequired()
                        .HasConstraintName("FK__souscript__id_st__412EB0B6");

                    b.Navigation("IdStatutSouscriptionNavigation");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Article", b =>
                {
                    b.Navigation("CaracteristiquesArticles");

                    b.Navigation("PrixArticles");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.CoordonneesBancaire", b =>
                {
                    b.Navigation("Prospects");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Financement", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Ligne", b =>
                {
                    b.Navigation("LigneArticles");

                    b.Navigation("LigneOptions");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.OffreEngagement", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("PrixArticles");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Option", b =>
                {
                    b.Navigation("Financements");

                    b.Navigation("LigneOptions");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.Souscription", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Lapostemobile_portail.Models.StatutSouscription", b =>
                {
                    b.Navigation("Souscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
